# File generated by CompCert 3.0.1
# Command line: -dasm fac.c
	.text
	.globl fac
fac:
	subl	$28, %esp
	leal	32(%esp), %eax
	movl	%eax, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	0(%eax), %ebx
	testl	%ebx, %ebx
	je	.L100
	leal	-1(%ebx), %eax
	movl	%eax, 0(%esp)
	call	fac
	imull	%eax, %ebx
	jmp	.L101
.L100:
	movl	$1, %ebx
.L101:
	movl	%ebx, %eax
	movl	8(%esp), %ebx
	addl	$28, %esp
	ret
	.type	fac, @function
	.size	fac, . - fac
	.data
	.globl	gv
gv:
	.long	0
	.type	gv, @object
	.size	gv, . - gv
	.text
	.globl main
main:
	subl	$12, %esp
	leal	16(%esp), %eax
	movl	%eax, 4(%esp)
	movl	$4, %eax
	movl	%eax, 0(%esp)
	call	fac
	movl	%eax, gv
	addl	$12, %esp
	ret
	.type	main, @function
	.size	main, . - main
