# File generated by CompCert 3.0.1
# Command line: -dasm fac.c -o fac
	.text
	.align	16
	.globl fac
fac:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	0(%eax), %ebx
	testl	%ebx, %ebx
	je	.L100
	leal	-1(%ebx), %eax
	movl	%eax, 0(%esp)
	call	fac
	imull	%eax, %ebx
	jmp	.L101
.L100:
	movl	$1, %ebx
.L101:
	movl	%ebx, %eax
	movl	8(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	fac, @function
	.size	fac, . - fac
	.comm	gv, 4, 4
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 4(%esp)
	movl	$4, %eax
	movl	%eax, 0(%esp)
	call	fac
	movl	%eax, gv
	addl	$12, %esp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
